image: maven:3-jdk-8

cache:
  paths:
    - .m3/repository/
    - target/

test:
  stage: test
  script:
    - ls -la
    - mvn clean test
  tags:
    - beton
  after_script:
    - mvn allure:report
    artifacts:
      when: always
      name: "report"
      paths:
        - $CI_PROJECT_DIR/target/site/allure-maven-plugin/
      expire_in: 15 days
